/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package display;

import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import path.structs.Point;

/**
 *
 * @author alexhuleatt
 */
public class Panel extends javax.swing.JPanel {

    public int sz, xCount, yCount;
    public static int ANIMATION_TIME = 10;
    public HashMap<Point, Integer> times;
    public HashSet<Point> visited;
    public HashSet<Point> obs;
    public Point start, finish;
    public ArrayList<Point> path;

    public Panel() {
        initComponents();
        times = new HashMap<>();
        visited = new HashSet<>();
    }

    public void clear() {
        times.clear();
        path = null;
        visited.clear();
        //obs.clear();
    }

    public void givePath(ArrayList<Point> path) {
        this.path = path;
    }

    public void activate(int x, int y) throws InterruptedException {
        Point p = new Point(x, y);

//        HashMap<Point, Integer> new_times = new HashMap<>();
//        new_times.put(p, 1);
        HashSet<Point> newVisited = new HashSet<>();
        newVisited.addAll(visited);
        newVisited.add(p);
//        for (Point t : times.keySet()) {
//            int old_time = times.get(t);
//            if (old_time < 1) {
//                new_times.put(t, old_time + 1);
//            }
//
//        }
        visited = newVisited;
//        times = new_times;
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                repaint();
            }
        });
        Thread.sleep(0);
    }

    public void setStart(int x, int y) {
        start = new Point(x, y);
    }

    public void setFinish(int x, int y) {
        finish = new Point(x, y);
    }

    public void setObs(HashSet<Point> obs) {
        this.obs = obs;
    }

    @Override
    public void paint(Graphics g) {
        g.setColor(Color.WHITE);
        g.fillRect(0, 0, sz * xCount, sz * yCount);
//        g.setColor(Color.black);
//        for (int i = 0; i < xCount; i++) {
//            g.drawLine(i * sz, 0, i * sz, yCount * sz);
//        }
//
//        for (int i = 0; i < yCount; i++) {
//            g.drawLine(0, i * sz, xCount * sz, i * sz);
//        }
//        

        g.setColor(Color.GRAY);
        for (Point p : visited) {
            g.fillRect(sz * p.x, sz * p.y, sz, sz);
        }

        g.setColor(Color.BLUE);
        g.fillRect(sz * start.x, sz * start.y, sz, sz);

        g.setColor(Color.MAGENTA);
        g.fillRect(sz * finish.x, sz * finish.y, sz, sz);
        g.setColor(Color.BLACK);
        for (Point p : obs) {
            g.fillRect(sz * p.x, sz * p.y, sz, sz);
        }
//        for (Point p : times.keySet()) {
//            g.setColor(new Color(255, 0, 0));
//            g.fillRect(sz * p.x - sz, sz * p.y - sz, sz * 3, sz * 3);
//        }
        if (path != null) {
            g.setColor(Color.GREEN);
            for (Point p : path) {
                g.fillRect(sz * p.x, sz * p.y, sz, sz);
            }
        }
    }

    public void myInit(int sz, int xCount, int yCount) {
        setSize(xCount * sz, sz * yCount);
        this.sz = sz;
        this.xCount = xCount;
        this.yCount = yCount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
